# Generated by Django 5.0.4 on 2024-04-24 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('totalReviewCount', models.IntegerField()),
                ('productionDate', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('brandName', models.CharField(max_length=200)),
                ('productCode', models.IntegerField()),
                ('imageUrl', models.CharField(max_length=200)),
                ('imageone', models.CharField(max_length=200)),
                ('imagetwo', models.CharField(max_length=200)),
                ('imagethree', models.CharField(max_length=200)),
                ('imagefour', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userImage', models.FilePathField()),
                ('location', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reviewTitle', models.CharField(max_length=200)),
                ('reviewText', models.CharField(max_length=200)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
