# Generated by Django 5.0.4 on 2024-04-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='isInStock',
            field=models.BooleanField(default=True),
        ),
    ]
